### ISSUE TITLE
Bug: Doesn't work under macos arm64

### ISSUE THREAD

**Issue by 0x1227** [SpaiR/imgui-java#226]
### Version

1.86.11

### What happened?

Doesn't work under macos arm64

### Reproduction

```
public class Example extends Application {

    @Override
    public void process() {
        ImGui.text("test");
    }

    public static void main(String[] args) {
        launch(new Example());
        System.exit(0);
    }
}

```

### Relevant log output

```bash
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/6d/_gcky1g57sj4dgs1h169xnvc0000gn/T/imgui-java-natives/1.86.11/libimgui-java64.dylib: dlopen(/private/var/folders/6d/_gcky1g57sj4dgs1h169xnvc0000gn/T/imgui-java-natives/1.86.11/libimgui-java64.dylib, 0x0001): tried: '/private/var/folders/6d/_gcky1g57sj4dgs1h169xnvc0000gn/T/imgui-java-natives/1.86.11/libimgui-java64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/6d/_gcky1g57sj4dgs1h169xnvc0000gn/T/imgui-java-natives/1.86.11/libimgui-java64.dylib' (no such file), '/private/var/folders/6d/_gcky1g57sj4dgs1h169xnvc0000gn/T/imgui-java-natives/1.86.11/libimgui-java64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2021)
	at imgui.ImGui.<clinit>(ImGui.java:63)
	at imgui.app.Window.initImGui(Window.java:138)
	at imgui.app.Window.init(Window.java:49)
	at imgui.app.Application.initialize(Application.java:92)
	at imgui.app.Application.launch(Application.java:82)
```

**Comment by SpaiR** [comment]
Resolved #223
aarch64 support will be available in the next release
