### ISSUE TITLE
I won't support it macOS arm64

### ISSUE THREAD

**Issue by 0x1227** [SpaiR/imgui-java#94]
lwjgl 3.3.0 Added pair macOS arm64 support.
Hope you can upgrade to lwjgl 3.3.0!!!

```
[LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
        JVM platform:
                macOS aarch64 1.8.0_312
                OpenJDK 64-Bit Server VM v25.312-b07 by Azul Systems, Inc.
        Platforms available on classpath:
                linux/x64
                windows/x64
                macos/x64
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
        at org.lwjgl.system.Library.loadSystem(Library.java:164)
        at org.lwjgl.system.Library.loadSystem(Library.java:63)
        at org.lwjgl.system.Library.<clinit>(Library.java:51)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
        at imgui.app.Window.initWindow(Window.java:70)
        at imgui.app.Window.init(Window.java:48)
        at imgui.app.Application.initialize(Application.java:91)
        at imgui.app.Application.launch(Application.java:81)
        at Main.main(Main.java:96)
```

**Comment by SpaiR** [comment]
Binding won't get a support for the arm64 arch until GitHub will add a propper build toolchains to their pipeline.
You can still build locally binaries though.

**Comment by cseblog** [comment]
I am also geting this error when running on my MacOS M1
> Task :BetterMain.main() FAILED
[LWJGL] GLFW_VERSION_UNAVAILABLE error
	Description : NSGL: The targeted version of macOS does not support OpenGL 3.0 or 3.1 but may support 3.2 and above
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
		Window.initWindow(Window.java:59)
		Window.init(Window.java:28)
		BetterMain.main(BetterMain.java:4)
