### ISSUE TITLE
UnsatisfiedLinkError when upgrade imgui-java from 1.83.2 to 1.85.0

### ISSUE THREAD

**Issue by Illithidek** [SpaiR/imgui-java#95]
Hey, when I upgrade version from 1.83.2 to 1.85.0 I get following error:

`Exception in thread "main" java.lang.InternalError: java.lang.UnsatisfiedLinkError: 'short org.lwjgl.system.libffi.LibFFI.FFI_TYPE_DOUBLE()'
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:415)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:304)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:218)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:328)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)`

I suppose this can be made due to fact that I'm using lwjgl 3.3.0 instead 3.2.3 like imgui-java right now.
It's strange for this to happen in the new imgui release when in the old one I didn't have this problem, something has changed?
Thanks in advance for any answer!

**Comment by SpaiR** [comment]
It's strange. There were changes in the native part of the binding, but I can't see how they can be related to the exception log you've provided. Did you tried to run your stuff with  lwjgl 3.2.3? Is the problem connected with the difference in versions for real?

**Comment by Illithidek** [comment]
@SpaiR I just checked, when I change lwjgl to 3.2.3 it's works. The disadvantage is that I cannot then use SPIRV-Cross in vulcan, because it came in lwjgl 3.3.0. So maybe the best idea would be to upgrade lwjgl in imgui-java to 3.3.0?

**Comment by SpaiR** [comment]
Binding depends on lwjgl to provide glfw and opengl implementations. Basically, imgui-java-lwjgl3 package. It's optional, so you can copy-paste a content of that package to your local codebase and use any lwjgl version you want.

**Comment by Illithidek** [comment]
Yeah but I believe there is no reason to use an older version of lwjgl.
I maked PR for that: https://github.com/SpaiR/imgui-java/pull/96

**Comment by tlf30** [comment]
Interesting, I am running LWJGL 3.3.0 and not getting this error. But I fully support updating this library.
